### PR TITLE
disabling gcc's tree vectorize fixes segfault

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/khaledhosny/psautohint/issues/16

### CODE REVIEW

**Comment by anthrotype** [comment]
should we also add the `-fno-tree-vectorize` flag to CFLAGS in the libpsautohint/Makefile?

**Comment by khaledhosny** [comment]
Thanks!

**Comment by anthrotype** [comment]
I wonder if compiling with clang instead of gcc causes the same issue.

**Comment by anthrotype** [comment]
yes, I confirm clang doesn't segfault with -O3 (I tried both clang-3.8 and clang-3.9).
I run `CC=clang-3.9 python setup.py build` at the commit immediately before this PR.

the problem is distutils can only check if compiler is "unix", can't distinguish whether it's gcc or clang.
Anyway, I don't think it's a problem if tree-vectorize optimization is disabled.

**Comment by behdad** [comment]
It's either a gcc bug, or undefined-behavior in our code.  This is just a workaround.

**Comment by khaledhosny** [comment]
My thoughts exactly. I was planning to see if I can build with ubsan and see if it reports anything.

**Comment by anthrotype** [comment]
I recompiled with CFLAGS="-fsanitize=undefined" LDFLAGS="-fsanitize=undefined" and when I run make check I get hundreds of runtime errors like this

libpsautohint/src/auto.c:66:14: runtime error: member access within misaligned address 0x7fda19c9c974 for type 'struct _clrval', which requires 8 byte alignment

**Pull request merged**
